<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mehr.Domain\Mehr.Domain.csproj" />
    <ProjectReference Include="..\Mehr.Resources\Mehr.Resources.csproj" />
    <ProjectReference Include="..\Mehr.SharedKernel\Mehr.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Costs\Contracts\Exceptions\" />
    <Folder Include="Docs\Contracts\Dtos\" />
    <Folder Include="Zones\Contracts\Exceptions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="8.0.22" />
  </ItemGroup>

</Project>
